---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_daemon_options:
          log-driver: syslog
          log-opts: 
            syslog-address: "unixgram:///dev/log"
            tag: "docker/{{ '{{' }} .Name {{ '}}' }}"
